[package]
name = 'tinylint'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'tinylint'

[dependencies]
ast-grep = "0.12.5"
extendr-api = '*'
tree-sitter-r = { git = "https://github.com/r-lib/tree-sitter-r", branch = "next", version = "0.20.1" }
