keep:
  - any_duplicated
  - any_is_na
  - class_equals
  - double_assignment
  - equal_assignment
  - equals_na
  - expect_named
  - is_numeric
  - length_levels
  - length_test
  - lengths
  - library_call
  - literal_coercion
  - implicit_assignment
  - matrix_apply
  - nested_ifelse
  - numeric_leading_zero
  - outer_negation
  - paste
  - redundant_ifelse
  - right_assignment
  - semicolon
  - seq
  - T_and_F_symbol
  - undesirable_function
  - unreachable_code